### ISSUE TITLE
Hackathon III - Checklist

### ISSUE THREAD

**Issue by mcandeia** [deco-cx/community#1]
# Description

This is a simple checklist for some manual steps that should be taken to make sure the hackathon will be a success.

- [ ] Test all Loaders/Functions and verify its working
- [ ] Test all Sections and verify its working
- [ ] Test onboarding - should be possible to edit a component + deploy/ab-testing
- [ ] Discord channels for mentors should have been created
- [ ] Discord voice channel/text channels for Hackathon
- [ ] Verify if the agenda is clear for everyone
- [ ] Ensure that we're running on multiple OSs without any issue (windows/linux/darwin)
- [ ] Make sure the hackathon rules are clear

**Comment by matheusgr** [comment]
- [ ] Check documentation and examples
